In [2]:
import torch

# Tensor Puzzles

In an effort to decrease the amount of tensor operation whilst errors building and training deep nets, I have created this  notebook to become more comfortable. It is comprised of various tensor puzzles generated by GPT-4 and my answers to them.

Puzzles 1-10 are very basic but help set the foundation to complete later puzzles.

#### Puzzle 1

Create a tensor A of size 3x3 filled with 5s. Multiply A by 3 and then subtract a tensor B of ones (same size as A).

In [3]:
A = torch.ones(3,3)*5
print(A, A.shape)
A = A * 3
print(A)
B = torch.ones(3,3)
print(B)
print(A-B)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]) torch.Size([3, 3])
tensor([[15., 15., 15.],
        [15., 15., 15.],
        [15., 15., 15.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[14., 14., 14.],
        [14., 14., 14.],
        [14., 14., 14.]])


#### Puzzle 2: Advanced Indexing

Given a tensor C of random integers between 0 and 10, shape 4x4, replace all elements greater than 5 with the value 10.

In [4]:
C = torch.randint(0, 10, (4,4))
print(C, C.shape)
print(C > 5)
print(C[C>5])
C[C>5] = 10
print(C)

tensor([[4, 9, 0, 9],
        [8, 1, 7, 7],
        [5, 6, 4, 3],
        [2, 3, 0, 0]]) torch.Size([4, 4])
tensor([[False,  True, False,  True],
        [ True, False,  True,  True],
        [False,  True, False, False],
        [False, False, False, False]])
tensor([9, 9, 8, 7, 7, 6])
tensor([[ 4, 10,  0, 10],
        [10,  1, 10, 10],
        [ 5, 10,  4,  3],
        [ 2,  3,  0,  0]])


#### Puzzle 3: Reduction

Create a tensor D with values from 1 to 16, shaped as 4x4. Calculate the sum of the diagonal elements.

In [5]:
D = torch.randint(1, 17, (4,4))
print(D, D.shape)
print(D.diag(), D.diag().shape)
print(D.diag(diagonal=-1))
sum = torch.sum(D.diag(diagonal=0))
print(sum)

tensor([[ 8,  6, 16, 14],
        [13,  9, 10, 14],
        [ 6, 14,  7,  6],
        [ 9,  4, 12,  5]]) torch.Size([4, 4])
tensor([8, 9, 7, 5]) torch.Size([4])
tensor([13, 14, 12])
tensor(29)


#### Puzzle 4: Broadcasting and Addition

Create two tensors E of shape 4x1 with values [1, 2, 3, 4] and F of shape 1x4 with values [1, 2, 3, 4]. Perform element-wise addition using broadcasting.

In [6]:
E = torch.tensor([[1],[2],[3],[4]])
print(E, E.shape)
F = torch.tensor([[1,2,3,4]])
print(F, F.shape)
print(E+F)

tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]])


Under the hood, E is repeated horizontally until it is 4x4. F is repeated vertically until 4x4. Then, do element-wise addition.

#### Puzzle 5: Matrix Multiplication

Define two tensors G of shape 3x2 filled with 3s and H of shape 2x3 filled with 2s. Compute the matrix product of G and H.

In [7]:
G = torch.randint(3,4,(3,2))
H = torch.randint(3,4,(2,3))
print(G, G.shape)
print(H, H.shape)
print(G.matmul(H))

tensor([[3, 3],
        [3, 3],
        [3, 3]]) torch.Size([3, 2])
tensor([[3, 3, 3],
        [3, 3, 3]]) torch.Size([2, 3])
tensor([[18, 18, 18],
        [18, 18, 18],
        [18, 18, 18]])


In [8]:
G = torch.ones(3,2)*3
H = torch.ones(2,3) * 3
print(G)
print(H)
print(G.matmul(H))

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[18., 18., 18.],
        [18., 18., 18.],
        [18., 18., 18.]])


#### Puzzle 6: Concatenation and Reshaping
Concatenate two tensors I of shape 2x2 filled with 1s and J of shape 2x2 filled with 2s along dimension 1, then reshape the result to a shape of 2x4.

In [9]:
I = torch.ones(2,2)
J = I * 2
print(I, I.shape)
print(J, J.shape)
cat = torch.cat([I, J], dim=1)
print(cat)
cat = cat.reshape(4,2)
print(cat)

tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
tensor([[2., 2.],
        [2., 2.]]) torch.Size([2, 2])
tensor([[1., 1., 2., 2.],
        [1., 1., 2., 2.]])
tensor([[1., 1.],
        [2., 2.],
        [1., 1.],
        [2., 2.]])


#### Puzzle 7: Conditional Elements

Create a tensor K of shape 3x3 with random numbers. Create a binary tensor L of the same shape indicating where K is greater than 0.5.

In [10]:
K = torch.randn(3,3)
print(K, K.shape)
L = K > 0.5
print(L, L.shape)
L = L.long()
print(L)

tensor([[ 0.8516, -0.9950, -0.1631],
        [ 0.0301, -1.3335, -0.0365],
        [ 0.4628,  0.0410, -1.7215]]) torch.Size([3, 3])
tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]]) torch.Size([3, 3])
tensor([[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### Puzzle 8: In-place Operations

Given a tensor M of shape 5 filled with the number 4, multiply each element by 3 using an in-place operation.

In [11]:
M = torch.ones(5) * 4
print(M, M.shape)
M = M.mul_(3)
print(M, M.shape)

tensor([4., 4., 4., 4., 4.]) torch.Size([5])
tensor([12., 12., 12., 12., 12.]) torch.Size([5])


#### Puzzle 9: Type Conversion

Create a tensor N with integers [1, 2, 3]. Convert this tensor to a float tensor.

In [12]:
N = torch.tensor([1,2,3])
print(N, N.shape)
N = N.float()
print(N)

tensor([1, 2, 3]) torch.Size([3])
tensor([1., 2., 3.])


#### Puzzle 10: Unsqueeze and Squeeze
Create a tensor O with shape 10. Use unsqueeze to add a new dimension making it 10x1, then use squeeze to remove the singular dimension.

In [13]:
O = torch.randn(10)
print(O, O.shape)
O = O.unsqueeze(1)
print(O, O.shape)
O = O.squeeze()
print(O, O.shape)

tensor([-0.3861,  0.5020,  0.7746,  0.5061,  1.1236, -0.7467,  0.0966, -0.1932,
         0.5918,  0.9620]) torch.Size([10])
tensor([[-0.3861],
        [ 0.5020],
        [ 0.7746],
        [ 0.5061],
        [ 1.1236],
        [-0.7467],
        [ 0.0966],
        [-0.1932],
        [ 0.5918],
        [ 0.9620]]) torch.Size([10, 1])
tensor([-0.3861,  0.5020,  0.7746,  0.5061,  1.1236, -0.7467,  0.0966, -0.1932,
         0.5918,  0.9620]) torch.Size([10])


#### Puzzle 11: Reverse Dimension

Create a tensor P of size 5x5 filled with numbers from 1 to 25 (inclusive and row-wise). Reverse the order of elements in each row.



In [20]:
P = torch.tensor(range(1,26)).reshape(5,5)
print(P, P.shape)
P = torch.fliplr(P)
print(P)


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]) torch.Size([5, 5])
tensor([[ 5,  4,  3,  2,  1],
        [10,  9,  8,  7,  6],
        [15, 14, 13, 12, 11],
        [20, 19, 18, 17, 16],
        [25, 24, 23, 22, 21]])


In [21]:
P = torch.tensor(range(1,26)).view(5,5)
print(P, P.shape)
P = torch.flip(P, dims=[1])
print(P)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]) torch.Size([5, 5])
tensor([[ 5,  4,  3,  2,  1],
        [10,  9,  8,  7,  6],
        [15, 14, 13, 12, 11],
        [20, 19, 18, 17, 16],
        [25, 24, 23, 22, 21]])


#### Puzzle 12: Custom Reduction

Given a tensor Q of size 6 filled with random numbers, compute the geometric mean of its elements.

In [31]:
Q = torch.randn(6)
print(Q, Q.shape)
geo_mean = torch.prod(Q)
print(geo_mean)
power = float(1/6)
geo_mean = torch.pow(geo_mean, power)
print(geo_mean)

tensor([ 0.5644,  1.3747, -0.2716, -0.5961, -0.2198, -0.8024]) torch.Size([6])
tensor(0.0221)
tensor(0.5299)


#### Puzzle 13: Advanced Slicing and Operations

Create a tensor R of size 8x8. Fill the border of the tensor with the value 1 and the inner 6x6 grid with the value 0. Then, increment the border elements by the sum of the inner grid.

In [61]:
R = torch.ones(8,8) * 2
print(R, R.shape)
R[[0, -1], :] = 1.
R[:, [0, -1]] = 1.
print(R)
sum = torch.sum(R[1:-1, 1:-1])
print(sum)
R[[0, -1], :] += sum
R[1:-1, [0, -1]] += sum
print(R, R.shape)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]]) torch.Size([8, 8])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 2., 2., 2., 2., 2., 2., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor(72.)
tensor([[73., 73., 73., 73., 73., 73., 73., 73.],
        [73.,  2.,  2.,  2.,  2.,  2.,  2., 73.],
        [73.,  2.,  2.,  2.,  2.,  2.,  2., 73.],
        [73.,  2.,  2.,  2.,  2.,  2.,  2., 73.],
        [73.,  2.,  2.,  2.,  2.,  2.,  2., 73.],
        [73.,  2.,  2.,  2.,  2.,  2.,  2., 7

#### Puzzle 14: Masked Fill
Given a tensor S of random numbers with size 4x4, set all values that are less than the mean of the tensor to -1.

In [72]:
S = torch.randn(4,4)
print(S, S.shape)
mean = torch.mean(S)
print(mean)
print(S < mean)
S[S < mean] = -1
print(S)

tensor([[-0.0752, -0.4233,  0.4217, -0.2576],
        [-1.5835,  1.3960, -1.0319,  1.1391],
        [ 0.5125, -0.0198, -1.1216, -0.4891],
        [-0.6336, -0.7893, -0.8977, -1.8876]]) torch.Size([4, 4])
tensor(-0.3588)
tensor([[False,  True, False, False],
        [ True, False,  True, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
tensor([[-0.0752, -1.0000,  0.4217, -0.2576],
        [-1.0000,  1.3960, -1.0000,  1.1391],
        [ 0.5125, -0.0198, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000]])


In [73]:
S = torch.randn(4,4)
print(S, S.shape)
S[S< torch.mean(S)] = -1
print(S)

tensor([[ 0.1870, -0.1813, -0.0914, -0.7349],
        [ 1.9859,  0.3625, -1.3898, -0.1593],
        [ 0.3290,  0.3323,  0.3025, -0.9812],
        [ 1.1038, -0.0127, -0.6851, -0.3094]]) torch.Size([4, 4])
tensor([[ 0.1870, -1.0000, -1.0000, -1.0000],
        [ 1.9859,  0.3625, -1.0000, -1.0000],
        [ 0.3290,  0.3323,  0.3025, -1.0000],
        [ 1.1038, -1.0000, -1.0000, -1.0000]])


In [74]:
S = torch.randn(4,4)
S = S.masked_fill(S < torch.mean(S), -1)
print(S)

tensor([[-1.0000, -1.0000, -1.0000, -1.0000],
        [ 0.3932,  0.9183, -1.0000,  0.0510],
        [-1.0000,  1.6216,  0.8594,  0.6996],
        [-1.0000,  1.2725, -1.0000, -1.0000]])


#### Puzzle 15: Eigenvalues and Eigenvectors
Compute the eigenvalues and eigenvectors of a 3x3 matrix T filled with random numbers.

In [ ]:
T = torch.randn(3,3)


#### Puzzle 16: Non-linear Reduction
Create a tensor U of random numbers with size 10. Replace each number with its exponential, then compute the mean of the tensor.

In [83]:
U = torch.randn(10)
print(U, U.shape)
print(torch.mean(torch.exp(U)))


tensor([ 1.0925,  0.6161,  0.8839,  0.9645,  0.3352, -1.1114, -2.4282,  0.0088,
         0.0051, -1.6722]) torch.Size([10])
tensor(1.3895)


#### Puzzle 17: Strided Slicing
Extract every second element from the tensor V of size 10x10 starting from the second element in each row.

In [90]:
V = torch.tensor(range(0, 100)).view(10,10)
print(V, V.shape)
print(V[:, 1::2])

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]) torch.Size([10, 10])
tensor([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49],
        [51, 53, 55, 57, 59],
        [61, 63, 65, 67, 69],
        [71, 73, 75, 77, 79],
        [81, 83, 85, 87, 89],
        [91, 93, 95, 97, 99]])


#### Puzzle 18: Complex Condition
Create a tensor W of size 6x6 filled with random numbers. Replace every element that is greater than 0.2 and less than 0.8 with 0.

In [101]:
W = torch.randn(6,6)
print(W, W.shape)
condition = (W > 0.2) & (W<0.8)
print(W[condition])

tensor([[-0.3865, -0.2090,  1.4653, -1.1026,  0.6482,  1.1923],
        [-0.7044,  1.7708, -0.1433, -0.5593, -1.2785, -1.3937],
        [-1.5790, -1.1405,  0.0207, -0.8548,  1.3221, -0.8846],
        [-0.4275, -1.7166, -0.6850,  0.8962, -1.7043, -0.4727],
        [-1.8849, -0.5538, -0.1751,  0.5644,  0.1806,  2.0155],
        [-0.1362,  0.3868,  0.5401, -0.8029, -0.5396,  0.3171]]) torch.Size([6, 6])
tensor([0.6482, 0.5644, 0.3868, 0.5401, 0.3171])


#### Puzzle 19: Advanced Broadcasting and Stacking
Create two tensors X of shape 3x3 filled with 1s and Y of shape 3x3 filled with 2s. Stack these two tensors along a new dimension, then multiply the result by a tensor Z of shape 1x3x3 filled with the sequence [1, 2, 3].

In [114]:
X = torch.ones(3,3)
Y = torch.ones(3,3) * 2

stack = torch.stack([X, Y], dim=0)
print(stack, stack.shape)

Z = torch.tensor([1,2,3])
print(Z, Z.shape)
Z = torch.vstack([Z,Z,Z])
print(Z, Z.shape)
print(stack.mul(Z))
# print(Z.mul(stack))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]) torch.Size([2, 3, 3])
tensor([1, 2, 3]) torch.Size([3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) torch.Size([3, 3])
tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]],

        [[2., 4., 6.],
         [2., 4., 6.],
         [2., 4., 6.]]])
tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]],

        [[2., 4., 6.],
         [2., 4., 6.],
         [2., 4., 6.]]])


#### Puzzle 20 Inverse and Dot Product

Given two square matrices A1 and A2 each of size 4x4 filled with random numbers, compute the dot product of the inverse of A1 with A2.

In [120]:
A1 = torch.randn(4,4)
A2 = torch.randn(4,4)
print(A1, A1.shape)
print(A2, A2.shape)

A1_inv = A1.inverse()
print(A1_inv, A1_inv.shape)

print(A1_inv @ A2)

tensor([[-0.7410, -0.5633,  0.5375,  1.4342],
        [ 1.5845, -0.6745,  0.1014,  0.6025],
        [-0.4449,  1.1818, -1.5674,  1.3641],
        [ 1.7530,  0.3057, -1.0385, -1.2354]]) torch.Size([4, 4])
tensor([[ 0.7900,  1.8645, -0.3265, -0.3552],
        [-0.6628,  1.2029, -0.8063,  0.7183],
        [-0.5789,  0.2560, -0.4040, -0.2089],
        [-1.1615,  0.7989,  1.0874,  0.8002]]) torch.Size([4, 4])
tensor([[-1.2671,  0.9811,  0.1655, -0.8099],
        [-3.7344,  1.5619,  0.6862, -2.8161],
        [-2.7866,  1.4133,  0.1066, -2.4282],
        [-0.3797,  0.5906,  0.3151, -0.6144]]) torch.Size([4, 4])
tensor([[-8.0643e-01, -1.7870e+00, -1.3249e+00,  4.7212e-01],
        [-1.1119e+00, -7.1582e+00, -3.3798e+00,  5.1525e-02],
        [-3.7960e-01, -5.4083e+00, -2.9134e+00,  3.9592e-02],
        [-1.6022e-01, -4.0769e-01, -1.1477e+00,  1.6677e-03]])
